version: '2'

services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    links:
      - redis
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
